#!/bin/bash

CONFIG_PATH="/app/config.yaml"
CRON_FILE="/etc/cron.d/backup_jobs"
ENV_FILE="/app/.env"

if [ -f "$ENV_FILE" ]; then
    export $(grep -v '^#' "$ENV_FILE" | xargs)
fi

if [ -z "$EMAIL_HOST" ] || [ -z "$EMAIL_PORT" ] || [ -z "$EMAIL_USERNAME" ] || [ -z "$EMAIL_PASSWORD" ] || [ -z "$EMAIL_FROM" ] || [ -z "$ERROR_EMAIL_TO" ]; then
    echo "WARNING: Email configuration is incomplete. Email notifications will not be available."
    echo "Please refer to the documentation for required email environment variables:"
    echo "  EMAIL_HOST, EMAIL_PORT, EMAIL_USERNAME, EMAIL_PASSWORD, EMAIL_FROM, ERROR_EMAIL_TO"
    echo "Email notifications are disabled for this session."
else
    echo "Email configuration found. Error notifications will be sent to: $ERROR_EMAIL_TO"
fi

> $CRON_FILE
echo "# Backup jobs generated by backuperr" > $CRON_FILE

mkdir -p /var/log/backuperr

# Generate cron jobs
python3 -c "
import yaml
import os

CONFIG_PATH = os.getenv('CONFIG_PATH', '/app/config.yaml')
CRON_FILE = '$CRON_FILE'

with open(CONFIG_PATH, 'r') as file:
    config = yaml.safe_load(file)

with open(CRON_FILE, 'a') as cron:
    for folder in config['folders']:
        schedule = folder['schedule']
        path = folder['path']

        command = f'cd /app && python3 /app/backup.py --path {path}'
        log_file = f'/var/log/backuperr/backup_{path.replace(\"/\", \"_\")}.log'

        # Proper cron format with user specification for /etc/cron.d/
        cron_line = f'{schedule} root {command} >> {log_file} 2>&1'

        print(f'Adding backup job of {path} with schedule {schedule}')
        print(f'  Logs will be written to {log_file}')

        cron.write(cron_line + '\n')

    # Add required newline at end of cron file
    cron.write('\n')
"

chmod 0644 $CRON_FILE

echo "Generated cron file contents:"
cat $CRON_FILE

echo "Starting cron..."
cron -f
